name: Continuous Deploy
on: [push]
jobs:
  deploy:
    name: Push to EC2 Instance
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Deploy to EC2 instance
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{secrets.EC2_SSH_KEY}}
          SOURCE: "./"
          REMOTE_HOST: ${{secrets.REMOTE_HOST}}
          REMOTE_USER: "ubuntu"
          TARGET: "/home/ubuntu/backend"